version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb-latest:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_latest_data:/data/db

  mongodb-old:
    image: mongo:6.0  # starsza wersja
    ports:
      - "27018:27017"
    volumes:
      - mongo_old_data:/data/db

volumes:
  mysql_data:
  postgres_data:
  mongo_latest_data:
  mongo_old_data:
